"""Linux / io_uring UAPI integer constants (linux/io_uring.h and related)."""
from __future__ import annotations

# --- io_uring_setup flags (linux/io_uring.h) ---
IORING_SETUP_IOPOLL = 1 << 0
IORING_SETUP_SQPOLL = 1 << 1
IORING_SETUP_SQ_AFF = 1 << 2
IORING_SETUP_CQSIZE = 1 << 3
IORING_SETUP_CLAMP = 1 << 4
IORING_SETUP_ATTACH_WQ = 1 << 5
IORING_SETUP_R_DISABLED = 1 << 6
IORING_SETUP_SUBMIT_ALL = 1 << 7
IORING_SETUP_COOP_TASKRUN = 1 << 8
IORING_SETUP_TASKRUN_FLAG = 1 << 9
IORING_SETUP_SQE128 = 1 << 10
IORING_SETUP_CQE32 = 1 << 11
IORING_SETUP_SINGLE_ISSUER = 1 << 12
IORING_SETUP_DEFER_TASKRUN = 1 << 13
IORING_SETUP_NO_MMAP = 1 << 14
IORING_SETUP_REGISTERED_FD_ONLY = 1 << 15
IORING_SETUP_NO_SQARRAY = 1 << 16
IORING_SETUP_HYBRID_IOPOLL = 1 << 17
IORING_SETUP_CQE_MIXED = 1 << 18
IORING_SETUP_SQE_MIXED = 1 << 19
IORING_SETUP_SQ_REWIND = 1 << 20

# --- sqe->flags (IOSQE_*) ---
IOSQE_FIXED_FILE = 1 << 0
IOSQE_IO_DRAIN = 1 << 1
IOSQE_IO_LINK = 1 << 2
IOSQE_IO_HARDLINK = 1 << 3
IOSQE_ASYNC = 1 << 4
IOSQE_BUFFER_SELECT = 1 << 5
IOSQE_CQE_SKIP_SUCCESS = 1 << 6

# --- enum io_uring_op (kernel UAPI; values must match linux/io_uring.h) ---
IORING_OP_NOP = 0
IORING_OP_READV = 1
IORING_OP_WRITEV = 2
IORING_OP_FSYNC = 3
IORING_OP_READ_FIXED = 4
IORING_OP_WRITE_FIXED = 5
IORING_OP_POLL_ADD = 6
IORING_OP_POLL_REMOVE = 7
IORING_OP_SYNC_FILE_RANGE = 8
IORING_OP_SENDMSG = 9
IORING_OP_RECVMSG = 10
IORING_OP_TIMEOUT = 11
IORING_OP_TIMEOUT_REMOVE = 12
IORING_OP_ACCEPT = 13
IORING_OP_ASYNC_CANCEL = 14
IORING_OP_LINK_TIMEOUT = 15
IORING_OP_CONNECT = 16
IORING_OP_FALLOCATE = 17
IORING_OP_OPENAT = 18
IORING_OP_CLOSE = 19
IORING_OP_FILES_UPDATE = 20
IORING_OP_STATX = 21
IORING_OP_READ = 22
IORING_OP_WRITE = 23
IORING_OP_FADVISE = 24
IORING_OP_MADVISE = 25
IORING_OP_SEND = 26
IORING_OP_RECV = 27
IORING_OP_OPENAT2 = 28
IORING_OP_EPOLL_CTL = 29
IORING_OP_SPLICE = 30
IORING_OP_PROVIDE_BUFFERS = 31
IORING_OP_REMOVE_BUFFERS = 32
IORING_OP_TEE = 33
IORING_OP_SHUTDOWN = 34
IORING_OP_RENAMEAT = 35
IORING_OP_UNLINKAT = 36
IORING_OP_MKDIRAT = 37
IORING_OP_SYMLINKAT = 38
IORING_OP_LINKAT = 39
IORING_OP_MSG_RING = 40
IORING_OP_FSETXATTR = 41
IORING_OP_SETXATTR = 42
IORING_OP_FGETXATTR = 43
IORING_OP_GETXATTR = 44
IORING_OP_SOCKET = 45
IORING_OP_URING_CMD = 46
IORING_OP_SEND_ZC = 47
IORING_OP_SENDMSG_ZC = 48
IORING_OP_READ_MULTISHOT = 49
IORING_OP_WAITID = 50
IORING_OP_FUTEX_WAIT = 51
IORING_OP_FUTEX_WAKE = 52
IORING_OP_FUTEX_WAITV = 53
IORING_OP_FIXED_FD_INSTALL = 54
IORING_OP_FTRUNCATE = 55
IORING_OP_BIND = 56
IORING_OP_LISTEN = 57
IORING_OP_RECV_ZC = 58
IORING_OP_EPOLL_WAIT = 59
IORING_OP_READV_FIXED = 60
IORING_OP_WRITEV_FIXED = 61
IORING_OP_PIPE = 62
IORING_OP_NOP128 = 63
IORING_OP_URING_CMD128 = 64
IORING_OP_LAST = 65

# IORING_MSG_RING command types (enum io_uring_msg_ring_flags)
IORING_MSG_DATA = 0
IORING_MSG_SEND_FD = 1

# openat / statx / fallocate (Linux UAPI)
AT_FDCWD = -100
AT_REMOVEDIR = 0x200
AT_SYMLINK_NOFOLLOW = 0x100
IORING_FSYNC_DATASYNC = 1 << 0
STATX_BASIC_STATS = 0x000007FF
FALLOC_FL_KEEP_SIZE = 0x01
FALLOC_FL_ZERO_RANGE = 0x10
SPLICE_F_MOVE = 0x01
SPLICE_F_FD_IN_FIXED = 1 << 31

IORING_FILE_INDEX_ALLOC = 0xFFFFFFFF

IORING_TIMEOUT_ABS = 1 << 0
IORING_TIMEOUT_UPDATE = 1 << 1
IORING_TIMEOUT_BOOTTIME = 1 << 2
IORING_TIMEOUT_REALTIME = 1 << 3
IORING_LINK_TIMEOUT_UPDATE = 1 << 4
IORING_TIMEOUT_ETIME_SUCCESS = 1 << 5
IORING_TIMEOUT_MULTISHOT = 1 << 6
IORING_TIMEOUT_CLOCK_MASK = IORING_TIMEOUT_BOOTTIME | IORING_TIMEOUT_REALTIME
IORING_TIMEOUT_UPDATE_MASK = IORING_TIMEOUT_UPDATE | IORING_LINK_TIMEOUT_UPDATE

IORING_POLL_ADD_MULTI = 1 << 0
IORING_POLL_UPDATE_EVENTS = 1 << 1
IORING_POLL_UPDATE_USER_DATA = 1 << 2
IORING_POLL_ADD_LEVEL = 1 << 3

IORING_ASYNC_CANCEL_ALL = 1 << 0
IORING_ASYNC_CANCEL_FD = 1 << 1
IORING_ASYNC_CANCEL_ANY = 1 << 2
IORING_ASYNC_CANCEL_FD_FIXED = 1 << 3
IORING_ASYNC_CANCEL_USERDATA = 1 << 4
IORING_ASYNC_CANCEL_OP = 1 << 5

IORING_RECVSEND_POLL_FIRST = 1 << 0
IORING_RECV_MULTISHOT = 1 << 1
IORING_RECVSEND_FIXED_BUF = 1 << 2
IORING_SEND_ZC_REPORT_USAGE = 1 << 3
IORING_RECVSEND_BUNDLE = 1 << 4
IORING_SEND_VECTORIZED = 1 << 5

IORING_NOTIF_USAGE_ZC_COPIED = 1 << 31

IORING_ACCEPT_MULTISHOT = 1 << 0
IORING_ACCEPT_DONTWAIT = 1 << 1
IORING_ACCEPT_POLL_FIRST = 1 << 2

IORING_MSG_RING_CQE_SKIP = 1 << 0
IORING_MSG_RING_FLAGS_PASS = 1 << 1

IORING_FIXED_FD_NO_CLOEXEC = 1 << 0

IORING_NOP_INJECT_RESULT = 1 << 0
IORING_NOP_CQE32 = 1 << 5

IORING_CQE_F_BUFFER = 1 << 0
IORING_CQE_F_MORE = 1 << 1
IORING_CQE_F_SOCK_NONEMPTY = 1 << 2
IORING_CQE_F_NOTIF = 1 << 3
IORING_CQE_F_BUF_MORE = 1 << 4
IORING_CQE_F_SKIP = 1 << 5
IORING_CQE_F_32 = 1 << 15
IORING_CQE_BUFFER_SHIFT = 16

IORING_SQ_NEED_WAKEUP = 1 << 0
IORING_SQ_CQ_OVERFLOW = 1 << 1
IORING_SQ_TASKRUN = 1 << 2

IORING_CQ_EVENTFD_DISABLED = 1 << 0

IORING_ENTER_GETEVENTS = 1 << 0
IORING_ENTER_SQ_WAKEUP = 1 << 1
IORING_ENTER_SQ_WAIT = 1 << 2
IORING_ENTER_EXT_ARG = 1 << 3
IORING_ENTER_REGISTERED_RING = 1 << 4
IORING_ENTER_ABS_TIMER = 1 << 5
IORING_ENTER_EXT_ARG_REG = 1 << 6
IORING_ENTER_NO_IOWAIT = 1 << 7

IORING_URING_CMD_FIXED = 1 << 0

IORING_OFF_SQ_RING = 0
IORING_OFF_CQ_RING = 0x8000000
IORING_OFF_SQES = 0x10000000
IORING_OFF_PBUF_RING = 0x80000000
IORING_OFF_PBUF_SHIFT = 16
IORING_OFF_MMAP_MASK = 0xF8000000

IORING_RW_ATTR_FLAG_PI = 1 << 0

# sync_file_range(2) flags (Linux)
SYNC_FILE_RANGE_WAIT_BEFORE = 1
SYNC_FILE_RANGE_WRITE = 2
SYNC_FILE_RANGE_WAIT_AFTER = 4

# posix_fadvise(2) advice (POSIX / Linux)
POSIX_FADV_NORMAL = 0
POSIX_FADV_RANDOM = 1
POSIX_FADV_SEQUENTIAL = 2
POSIX_FADV_WILLNEED = 3
POSIX_FADV_DONTNEED = 4
POSIX_FADV_NOREUSE = 5

# madvise(2) — common Linux values
MADV_NORMAL = 0
MADV_RANDOM = 1
MADV_SEQUENTIAL = 2
MADV_WILLNEED = 3
MADV_DONTNEED = 4

# enum io_uring_socket_op (liburing/io_uring.h)
SOCKET_URING_OP_SIOCINQ = 0
SOCKET_URING_OP_SIOCOUTQ = 1
SOCKET_URING_OP_GETSOCKOPT = 2
SOCKET_URING_OP_SETSOCKOPT = 3
SOCKET_URING_OP_TX_TIMESTAMP = 4
SOCKET_URING_OP_GETSOCKNAME = 5

# Typical size for siginfo_t buffer passed to waitid(2) via io_uring
SIGINFO_T_SIZE = 128

# Kernel/io_uring UAPI integer symbols defined in this module (for pyuring package re-export).
_UAPI_PREFIXES = (
    "IORING_",
    "IOSQE_",
    "AT_",
    "SPLICE_F_",
    "FALLOC_FL_",
    "STATX_",
    "SYNC_FILE_RANGE_",
    "POSIX_FADV_",
    "MADV_",
    "SOCKET_URING_",
)
UAPI_CONSTANT_NAMES = tuple(
    sorted(
        name
        for name, val in list(globals().items())
        if isinstance(val, int) and not isinstance(val, bool) and any(name.startswith(p) for p in _UAPI_PREFIXES)
    )
)
del _UAPI_PREFIXES
